apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/noahgallodevoteam/argocd-test-app.git"
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
